services:
  discussion:
    image: node:16.15-alpine
    entrypoint:
      [
        'npx',
        'ts-node',
        'src/domains/Community/Discussion/infra/bootstrap/api.ts',
      ]
    working_dir: /app
    env_file:
      - src/core/App/infrastructure/.env.dev
      - .env.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgresql
      - kubemq

  # discussion:
  #   image: node:16.15-alpine
  #   entrypoint: ['npx', 'ts-node', './../di/app.ts']
  #   #    entrypoint: ['/bin/sh', '-c']
  #   #    command:
  #   #      - |
  #   #        npm install
  #   #        npm build
  #   #        npm db:migrate:latest
  #   #        npm start
  #   working_dir: /app
  #   env_file:
  #     - src/core/App/infrastructure/.env.dev
  #     - .env.dev
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   depends_on:
  #     - postgresql
  #     - kubemq

  # discussion-worker:
  #   image: node:16.15-alpine
  #   entrypoint: ['npx', 'ts-node', './../di/worker.ts']
  #   #    entrypoint: ['/bin/sh', '-c']
  #   #    command:
  #   #      - |
  #   #        npm install
  #   #        npm build
  #   #        npm worker
  #   working_dir: /app
  #   env_file:
  #     - src/core/App/infrastructure/.env.dev
  #     - .env.dev
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   depends_on:
  #     - discussion
