services:
  discussion:
    # image: node:16.15-alpine
    # entrypoint: ['npm', 'run', 'dev']
    # entrypoint: ['/bin/sh', '-c']
    # command: ['node', 'run', 'dev']
    build:
      context: ./../../../
      dockerfile: ./domains/Community/Discussion/docker/dev/Dockerfile
    working_dir: /app
    env_file:
      - ./../../../.env
      - .env
    ports:
      - 8081:8081
    # volumes:
    #   - ./src:/app/domains/Community/Discussion/src
    depends_on:
      - postgresql
      - kubemq

  # discussion:
  #   image: node:16.15-alpine
  #   entrypoint: ['npx', 'ts-node', './../di/app.ts']
  #   #    entrypoint: ['/bin/sh', '-c']
  #   #    command:
  #   #      - |
  #   #        npm install
  #   #        npm build
  #   #        npm db:migrate:latest
  #   #        npm start
  #   working_dir: /app
  #   env_file:
  #     - src/core/App/infrastructure/.env.dev
  #     - .env.dev
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   depends_on:
  #     - postgresql
  #     - kubemq

  # discussion-worker:
  #   image: node:16.15-alpine
  #   entrypoint: ['npx', 'ts-node', './../di/worker.ts']
  #   #    entrypoint: ['/bin/sh', '-c']
  #   #    command:
  #   #      - |
  #   #        npm install
  #   #        npm build
  #   #        npm worker
  #   working_dir: /app
  #   env_file:
  #     - src/core/App/infrastructure/.env.dev
  #     - .env.dev
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   depends_on:
  #     - discussion

  postgresql:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: game-store
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pwd
    volumes:
      - game-store-db:/var/lib/postgresql/data:rw

  kubemq:
    image: kubemq/kubemq
    ports:
      - 8080:8080
      - 9090:9090
      - 50000:50000
    environment:
      KUBEMQ_HOST: kubemq
      KUBEMQ_TOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    volumes:
      - broker-persistence:/store

volumes:
  game-store-db:
  broker-persistence:
