services:
  discussion:
    build:
      context: ./../../../
      dockerfile: ./domains/Community/Discussion/docker/dev/Dockerfile
    working_dir: /app
    env_file:
      - ./../../../.env
      - .env
    ports:
      - 8081:8081
    volumes:
      - ./../../SharedKernel/src:/app/domains/SharedKernel/src:ro
      - ./src:/app/domains/Community/Discussion/src:ro
    depends_on:
      - postgresql
      - kubemq

  postgresql:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: game-store
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pwd
    volumes:
      - game-store-db:/var/lib/postgresql/data:rw

  kubemq:
    image: kubemq/kubemq
    ports:
      - 8080:8080
      - 9090:9090
      - 50000:50000
    environment:
      KUBEMQ_HOST: kubemq
      KUBEMQ_TOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    volumes:
      - broker-persistence:/store

volumes:
  game-store-db:
  broker-persistence:
