/** Declaration file generated by dts-gen */
declare module "correlation-id" {
  export function bindId(id: any, work?: any): any;

  export function getId(): any;

  export function withId(id: any, work?: any): any;
}
